services:
  # Servicio PHP
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/symfony:cached
    working_dir: /var/www/symfony
    ports:
      - "9000:9000"
    depends_on:
      - mailhog

  # Servicio MySQL
  db:
    image: mysql:8.0
    container_name: symfony_mysql
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:stable
    ports:
        - "8080:80"
    volumes:
        - ./:/var/www/symfony
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    container_name: symfony_mercure
    ports:
      -  "3000:80"
    environment:
      SERVER_NAME: ':80'

      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'

      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive

      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins "http://localhost:8080"
        publish_allowed_origins "*"
        anonymous
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s

    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Interfaz web de MailHog
      - "1025:1025" # Puerto SMTP

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
